Repository codestates-seb/seb40_main_001, pull requests merged in 2022-12, with the labels that each got.

#194 ✨ feat: 메인페이지 추가수정
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/pages/Login.js
Labels: Front, Feat

#198 🐛 fix: 분기 로직 변경 및 개선 완료
  client/src/components/UI/atoms/HomeCardLayouts.js
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/pages/Main.js
Labels: Front, Fix

#179 ✨ Feat: Access Token 만료 시에 Refresh Token을 통해 재발급하는 로직 구현
  server/src/main/java/com/ilchinjo/mainproject/domain/auth/entity/RefreshToken.java
  server/src/main/java/com/ilchinjo/mainproject/domain/auth/repository/RefreshTokenRepository.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/jwt/JwtTokenizer.java
Labels: Back, Feat

#196 ✨ Feat: 주소 지리좌표 데이터 적용
  server/build.gradle
  server/geoscript/geojson_to_sql_for_mysql_5179_seoul.py
  server/src/main/java/com/ilchinjo/mainproject/domain/address/controller/AddressController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/entity/Address.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/repository/AddressRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressServiceImpl.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
Labels: Back, Feat

#199 ✨Feat: 마이페이지 일부 구현, api 요청 이슈 해결
  client/src/App.js
  client/src/assets/img/icons/confirm.svg
  client/src/assets/img/icons/edit.svg
  client/src/client/client.js
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/molecules/NicknameMypage.js
  client/src/components/UI/organisms/ArounderRecord.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/UI/organisms/MyInfo.js
  client/src/components/pages/Login.js
  client/src/components/pages/Mypage.js
  client/src/components/pages/Register.js
  client/src/index.css
Labels: Front, Feat, Fix

#201 🐛 Fix: ExerciseRecordDto에 Address엔티티가 들어있는 부분 수정
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseRecordDto.java
Labels: Back, Fix

#204 🩹 Chore: member info에 프로필사진정보 포함
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberSimpleDto.java
Labels: Back, Chore

#208 ♻️ Refactor: 운동모집 전체조회에서 Querydsl 사용
  server/build.gradle
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryCustom.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryCustomImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Refactor

#209 ✨Feat: 마이페이지 구현
  client/src/assets/img/icons/edit.svg
  client/src/components/UI/atoms/EditBtn.js
  client/src/components/UI/atoms/ImgAddBtn.js
  client/src/components/UI/molecules/NicknameMypage.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/UI/organisms/MyInfo.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
Labels: Front, Feat

#193 ✨feat: 상세페이지 70% 정도 구현
  client/src/components/UI/atoms/CommentDeleteBtn.js
  client/src/components/UI/atoms/TextInput.js
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/molecules/Carousel.js
  client/src/components/UI/molecules/InputComments.js
  client/src/components/UI/organisms/DetailContents.js
  client/src/components/UI/organisms/DetailContentsWriter.js
  client/src/components/UI/organisms/ViewerComments.js
  client/src/components/UI/organisms/WriterComments.js
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
  client/src/components/pages/Landing.js
  client/src/components/pages/Main.js
Labels: Front, Fix

#210 ✨feat: 클라이언트 디폴트 및 인터셉터 진행중
  client/src/client/client.js
  client/src/components/UI/atoms/HomeCardImg.js
Labels: Front, Feat

#212 🩹chore: ArounderViewer props 정정
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
Labels: Front, Chore, Fix

#213 🚑Hotfix: 마이페이지 랜딩 오류 해결
  client/src/components/pages/Mypage.js
Labels: Front, Fix

#216 ✨feat: 드로워 추가
  client/package-lock.json
  client/package.json
  client/src/components/pages/Main.js
  client/src/index.css
  client/tailwind.config.js
Labels: Front, Feat

#223 🐛 Bug: 운동모집글 수정에 누락됐던 이미지 수정 로직 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePatchDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java
Labels: Back, Fix

#224 🐛 Bug: 동일한 사람이 여러번 신청할 수 없는 로직 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Fix

#222 🚑hotfix: 마이페이지 이미지 렌더 오류 수정
  client/src/components/UI/atoms/ShortBtn.js
  client/src/components/UI/molecules/ArounderReview.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/molecules/NicknameMypage.js
  client/src/components/UI/organisms/Modal.js
  client/src/components/UI/organisms/MyInfo.js
  client/src/components/pages/Mypage.js
Labels: Front, Fix

#219 ✨ Feat: Refresh POST API 생성
  server/src/main/java/com/ilchinjo/mainproject/domain/auth/controller/AuthController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/auth/repository/RefreshTokenRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/auth/service/AuthService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/auth/service/AuthServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/jwt/JwtStatus.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/jwt/JwtTokenizer.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/utils/ErrorResponder.java
Labels: Back, Feat

#225 🐛 Bug: 운동모집 글의 성별타입이 SAME일 때, 이성이 신청 못하게하는 로직 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Fix

#226 ✨feat: (대)댓글 작성/삭제 구현 && 게시물 수정/삭제 구현
  client/src/components/UI/molecules/CommentViewer_X.js
  client/src/components/UI/molecules/InputComments.js
  client/src/components/UI/molecules/WriterCardLayouts_X.js
  client/src/components/UI/organisms/ViewerComments.js
  client/src/components/UI/organisms/WriterComments.js
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
Labels: Front, Feat

#229 #218 🩹chore: 무한스크롤 사이즈 조절 및 로그인 이슈
  client/src/components/pages/Login.js
  client/src/components/pages/Main.js
Labels: Front, Fix

#231 ✨ Feat: 닉네임 중복일 때 에러코드 생성
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#233 ✨feat: 이메일,닉네임 중복 알림 처리
  client/src/components/pages/Login.js
  client/src/components/pages/Main.js
  client/src/components/pages/Register.js
Labels: Front, Fix

#236 #235 ✨feat: 뷰어 기준 함께하기 신청 가능
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/organisms/ViewerComments.js
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
Labels: Front, Feat

#237 🐛Bug: 글쓰기 페이지 버그 수정
  client/src/components/UI/atoms/Datepicker.js
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/atoms/WriteContentsInput.js
  client/src/components/UI/atoms/WriteTitleInput.js
  client/src/components/UI/molecules/AddFile.js
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/UI/molecules/ExerciseCategory.js
  client/src/components/UI/molecules/WriteDate.js
  client/src/components/UI/molecules/WriteGenderSelect.js
  client/src/components/UI/molecules/WriteHNC.js
  client/src/components/UI/organisms/WriteContents.js
  client/src/components/pages/ArounderWriter.js
  client/src/components/pages/Write.js
Labels: Front, Fix

#238 🩹chore : 무한 리렌더링 방지 및 댓글 창 높이 제한 해제
  client/src/components/UI/atoms/CommentLayout.js
  client/src/components/UI/atoms/WriterCommentLayout.js
  client/src/components/UI/molecules/Applicant.js
Labels: Front, Chore, Fix

#239 #211 ✨feat: 드로워 추가 기능 구현
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/pages/Main.js
  client/src/components/pages/Register.js
Labels: Front, Feat

#240 ✨feat: 어라운더 신청하기/확정하기 구현
  client/src/components/UI/atoms/CarouselBtn.js
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/molecules/Carousel.js
  client/src/components/UI/organisms/WriterComments.js
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
Labels: Front, Feat

#241 🩹 chore: drawer 및 client 수정
  client/src/client/client.js
  client/src/components/pages/Login.js
  client/src/components/pages/Main.js
Labels: Front, Fix

#242 #211 🩹chore: 메인 게시글 첫 랜딩 401 에러 수정완료
  client/src/components/pages/Login.js
Labels: Front, Fix

#244 🐛bug: 마이페이지 렌더 지연 문제 해결
  client/src/components/UI/molecules/NicknameMypage.js
  client/src/components/UI/organisms/MyInfo.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
Labels: Front, Fix

#246 🐛bug: 이미지 수정 버튼 움직임 제거
  client/src/components/UI/organisms/MyInfo.js
Labels: Front, Chore

#247 💄ui: 드로워 수정
  client/src/components/UI/organisms/ArounderRecord.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
Labels: Front, Chore, UI

#249 ✅ test: 쿠키 테스트
  client/src/components/pages/Main.js
Labels: Front, Feat

#250 ✅ test: client 수정
  client/src/client/client.js
Labels: Front, Fix

#253 🐛bug: LongBtn 사이드이펙트 제거
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/pages/Write.js
Labels: Front, Fix

#252 ✨ feat: 헤더 ui 추가
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/UI/molecules/HeaderLogo.js
Labels: Front, Feat

#248 ✨feat: 어플리컨트 해결 및 버그 픽스 등
  client/src/components/UI/atoms/HomeCardLayouts.js
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/organisms/DetailContents.js
  client/src/components/UI/organisms/DetailContentsWriter.js
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
Labels: Front, Feat, Fix

#256 :recycle: Refactor: GenderType Qureydsl 수정
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryImpl.java
Labels: Back, Refactor

#258 🐛 Fix: 신청 전체 조회 시 중복되어서 조회되는 문제 수정
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/repository/ProposalRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
  server/src/main/resources/application.yml
Labels: Back, Fix

#263 🩹chore : 캐러셀 수정
  client/src/components/UI/molecules/Carousel.js
Labels: Front, Fix

#265 ✨ feat: refresh 토큰 추가 설정
  client/src/client/client.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/UI/organisms/MyInfo.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
Labels: Front, Feat

#266 🩹 Chore: 모든 엔티티 ManyToOne LazyLoading으로 전환
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/entity/Comment.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/entity/Reply.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/entity/Review.java
Labels: Back, Chore

#260 🐛 Fix: Refresh Token Cookie의 도메인 옵션 추가
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtAuthenticationFilter.java
Labels: Back, Feat

#273 🐛Bug: 글쓰기 페이지 버그 수정
  client/src/components/UI/atoms/Datepicker.js
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/pages/Main.js
  client/src/components/pages/Write.js
Labels: Front, Fix

#274 :bug: Bug: 수락 로직에 시간 제약 조건 설정
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
Labels: Back, Fix

#276 🩹 Chore: 기본 batch fetch size 설정
  server/src/main/resources/application.yml
Labels: Back, Feat

#280 🐛 Bug: 일부 OneToOne에 lazy로딩 제거
  server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
Labels: Back, Fix

#283 ✨ Feat: healthcheck api 생성
  server/src/main/java/com/ilchinjo/mainproject/global/controller/HealthCheckController.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
Labels: Back, Feat

#279 🩹chore: 날짜 시간 기준 모집종료 로직 추가
  client/src/components/UI/molecules/Applicant.js
Labels: Front, Chore, Fix

#282 ✨feat: 메타태그 추가
  client/package-lock.json
  client/package.json
  client/public/AroundImg.png
  client/public/around.png
  client/src/client/client.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/meta/MetaTag.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
  client/src/index.js
Labels: Front, Feat

#278 🐛Fix: 마이페이지 버그 수정
  client/src/components/UI/molecules/CommentViewer_X.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/organisms/Modal.js
  client/src/components/pages/Mypage.js
  client/src/components/pages/Write.js
  client/src/index.css
Labels: Front, Fix

#285 ✨ feat: 추가 수정
  client/src/client/client.js
  client/src/components/meta/MetaTag.js
Labels: Front, Feat

#286 📝docs: readme update
  Readme.md
Labels: Docs

#287 📝docs: readme update
  Readme.md
Labels: Docs

#289 🩹chore: 리드미 수정
  Readme.md
Labels: Front, Fix

#293 :bug: Bug: 운동모집글 수정시에도 시간제약 조건 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
Labels: Back, Fix

#294 🐛 Bug: 모든 post patch dto에서 원시타입 제거
  server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
Labels: Back, Fix

#295 🐛Bug: 배포 후 QA 내용 적용
  client/src/components/UI/atoms/ShortBtn.js
  client/src/components/UI/molecules/ArounderReview.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/organisms/DetailContents.js
  client/src/components/pages/Mypage.js
  client/src/components/pages/Write.js
Labels: Front, Fix

#296 Develop to main
  Readme.md
  client/package-lock.json
  client/package.json
  client/public/AroundImg.png
  client/public/around.png
  client/src/client/client.js
  client/src/components/UI/atoms/Datepicker.js
  client/src/components/UI/atoms/ShortBtn.js
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/molecules/ArounderReview.js
  client/src/components/UI/molecules/CommentViewer_X.js
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/organisms/DetailContents.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/UI/organisms/Modal.js
  client/src/components/meta/MetaTag.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
  client/src/components/pages/Write.js
  client/src/index.css
  client/src/index.js
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/global/controller/HealthCheckController.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
Labels: Test

#297 🐛bug: QA 버그 수정 완료
  client/src/components/UI/organisms/ViewerComments.js
  client/src/components/UI/organisms/WriterComments.js
  client/src/components/pages/ArounderWriter.js
Labels: Front, Fix

#299 #298 🐛 Bug : 메인페이지 카드 수정
  client/src/components/UI/organisms/HomeContents.js
Labels: Front, Fix

#300 #290 🐛 Bug : 리뷰 버그 수정
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/organisms/Modal.js
  client/src/components/pages/Mypage.js
  client/src/components/pages/Write.js
Labels: Front, Fix

#301 🐛bug: 어라운더 확정 하기 전에 알림 창 추가
  client/src/components/UI/molecules/Applicant.js
Labels: Front, Fix

#304 #290 🔥remove: 콘솔 제거
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/molecules/HeaderFind.js
  client/src/components/UI/organisms/DetailContents.js
Labels: Front, Fix

#305 #302 🐛 Bug : key 에러 수정
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/organisms/ViewerComments.js
Labels: Front, Fix

#306 #290 🐛bug: 날짜 비교 에러 수정
  client/src/components/pages/Write.js
Labels: Front, Fix

#307 🐛 Bug : key 에러 수정
  client/src/components/UI/organisms/WriterComments.js
Labels: Front, Fix

#308 #298 🐛 Fix : cursorId 수정
  client/src/components/pages/Main.js
Labels: Front, Feat

#310 🐛bug: 대댓글 밸류값 수정
  client/src/components/pages/ArounderWriter.js
Labels: Front, Fix

#309 #290 🐛bug: 작성자 시점에서 엔터 적용
  client/src/components/UI/organisms/DetailContentsWriter.js
Labels: Front, Fix

#311 #290 🐛bug: 운동 시간 검증로직 수정
  client/src/components/pages/Write.js
Labels: Front, Fix

#313 🐛 Fix : 무한스크롤 수정
  client/src/components/pages/Main.js
Labels: Front, Fix

#315 #290 🐛bug: 시간 알람 버그 해결
  client/src/components/pages/Write.js
Labels: Front, Fix

#316 #298 🐛 Fix : 무한스크롤 롤백
  client/src/components/pages/Main.js
Labels: Front, Fix

#314 🐛bug: QA 버그 수정 완료
  client/src/components/UI/molecules/Applicant.js
  client/src/components/UI/molecules/HeaderFind.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/organisms/DetailContents.js
  client/src/components/UI/organisms/DetailContentsWriter.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/components/UI/organisms/Modal.js
  client/src/components/UI/organisms/ViewerComments.js
  client/src/components/UI/organisms/WriterComments.js
  client/src/components/pages/ArounderWriter.js
  client/src/components/pages/Main.js
  client/src/components/pages/Mypage.js
  client/src/components/pages/Write.js
Labels: Fix, Test

#321 ✨ feat: 무한스크롤 cursorId 로직 개선
  client/src/components/pages/Main.js
Labels: Front, Feat, Refactor
