Repository codestates-seb/seb40_main_001, pull requests merged in 2022-11, with the labels that each got.

#16 ✨ Feat: 백엔드 초기 세팅
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/ilchinjo/mainproject/MainprojectApplication.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/entity/Address.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/entity/Comment.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Category.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/ExerciseStatus.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/GenderType.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Gender.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/entity/Reply.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/entity/Review.java
  server/src/main/java/com/ilchinjo/mainproject/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/ilchinjo/mainproject/global/audit/AuditingEntity.java
  server/src/main/java/com/ilchinjo/mainproject/global/config/WebConfig.java
  server/src/main/java/com/ilchinjo/mainproject/global/dto/MultiResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/global/dto/PageInfo.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/BusinessLogicException.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
  server/src/main/java/com/ilchinjo/mainproject/global/response/ErrorResponse.java
  server/src/main/resources/application.yml
  server/src/test/java/com/ilchinjo/mainproject/MainprojectApplicationTests.java
Labels: Back, Feat

#17 ✨ Feat: 프론트엔드 초기 세팅
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc.js
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/tailwind.config.js
Labels: Front, Feat

#24 💄 ui : tailwind config 설정
  client/.eslintrc.js
  client/tailwind.config.js
Labels: Front, UI

#25 🩹chore : daisy와 충돌 수정
  client/tailwind.config.js
Labels: Front, Chore, UI

#33 ✨ Feat: 회원 가입 POST API
  server/build.gradle
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/repository/MemberRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#34 ✨ Feat: 운동모집 글 PATCH API 구현
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePatchDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
Labels: Back, Feat

#35 ✨fear: Add input/ cardlayouts/ImgLayouts
  client/src/App.js
  client/src/components/CardLayouts/CommentViewer.js
  client/src/components/CardLayouts/HistoryCardLayouts.js
  client/src/components/CardLayouts/HomeCardLayouts.js
  client/src/components/CardLayouts/WriterCardLayouts.js
  client/src/components/ImgLayouts/Applicant.js
  client/src/components/ImgLayouts/Drawer.js
  client/src/components/ImgLayouts/HNM.js
  client/src/components/ImgLayouts/HomeCardImg.js
  client/src/components/ImgLayouts/HomeCardSquare.js
  client/src/components/ImgLayouts/SignupImg.js
  client/src/components/Inputs/Input.js
  client/src/components/Inputs/TextInput.js
  client/src/index.js
  client/tailwind.config.js
Labels: Front, Feat

#37 ✨ Feat: 회원 정보 수정 PATCH API
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
Labels: Back, Feat

#38 ♻️ Refactor: 운동모집 글과 회원 연관관계 매핑
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Refactor

#39 💄ui : tailwind config 추가
  client/tailwind.config.js
Labels: Front, UI

#40 ✨ Feat: 주소 전체조회 API
  server/src/main/java/com/ilchinjo/mainproject/domain/address/controller/AddressController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/dto/AddressResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/mapper/AddressMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/repository/AddressRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/dto/MultiResponseDto.java
Labels: Back, Feat

#41 ✨feat : button atom 구현
  client/.eslintrc.js
  client/src/assets/img/icons/all.svg
  client/src/assets/img/icons/basketball.svg
  client/src/assets/img/icons/commentDelete.svg
  client/src/assets/img/icons/delete.svg
  client/src/assets/img/icons/edit.svg
  client/src/assets/img/icons/fileDelete.svg
  client/src/assets/img/icons/imgAdd.svg
  client/src/assets/img/icons/light.svg
  client/src/assets/img/icons/running.svg
  client/src/assets/img/icons/swim.svg
  client/src/assets/img/icons/tennis.svg
  client/src/assets/img/icons/update.svg
  client/src/assets/img/icons/weight.svg
  client/src/assets/img/icons/yoga.svg
  client/src/components/UI/atoms/ChooseBtn.js
  client/src/components/UI/atoms/CommentBtn.js
  client/src/components/UI/atoms/CommentDeleteBtn.js
  client/src/components/UI/atoms/DeleteBtn.js
  client/src/components/UI/atoms/EditBtn.js
  client/src/components/UI/atoms/ExerciseBtn.js
  client/src/components/UI/atoms/FileDeleteBtn.js
  client/src/components/UI/atoms/ImgAddBtn.js
  client/src/components/UI/atoms/LightBtn.js
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/atoms/MiniBtn.js
  client/src/components/UI/atoms/ShortBtn.js
  client/src/components/UI/atoms/UpdateBtn.js
Labels: Front, Feat

#42 ✨ Feat: 운친 함께하기 신청 POST API
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/dto/ProposalResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/mapper/ProposalMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/repository/ProposalRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#44 ✨feat : datepicker 구현 완료
  client/package-lock.json
  client/package.json
  client/src/components/UI/atoms/Datepicker.js
Labels: Front, Feat

#46 🩹chore : onClick 이벤트 추가
  client/src/components/UI/atoms/CommentBtn.js
  client/src/components/UI/atoms/EditBtn.js
  client/src/components/UI/atoms/ExerciseBtn.js
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/atoms/MiniBtn.js
  client/src/components/UI/atoms/ShortBtn.js
  client/src/components/UI/atoms/index.js
Labels: Front, Chore

#50 ✨feat : dropdown 구현
  client/src/assets/img/icons/downArrow.svg
  client/src/components/UI/molecules/Dropdown.js
  client/src/components/UI/molecules/MiniDropdown.js
Labels: Front, Feat

#51 ✨feat: Add Text MOLECULES
  client/src/components/UI/atoms/TextInput.js
  client/src/components/UI/molecules/ArounderReview.js
  client/src/components/UI/molecules/InputComments.js
  client/src/components/UI/molecules/WriterDetail.js
Labels: Front, Feat

#49 ✨ Feat: 댓글 작성 POST API
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/dto/CommentPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/dto/CommentResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/entity/Comment.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/mapper/CommentMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/repository/CommentRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentServiceImpl.java
Labels: Back, Feat

#52 ✨ Feat: 댓글 삭제 DELETE API
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#53 ✨ Feat: 신청리스트 조회 API
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/dto/ProposalSimpleResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/mapper/ProposalMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
Labels: Back, Feat

#55 ✨ Feat: 신청 수락 API
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#54 ✨feat : 캐러셀 구현
  client/src/components/UI/atoms/CarouselBtn.js
  client/src/components/UI/atoms/ExerciseBtn.js
  client/src/components/UI/atoms/index.js
  client/src/components/UI/molecules/Carousel.js
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/UI/molecules/ExerciseCategory.js
Labels: Front, Feat

#58 ✨ Feat: Add molecules Card
  client/src/assets/img/icons/basketball.svg
  client/src/assets/img/icons/running.svg
  client/src/assets/img/icons/swim.svg
  client/src/assets/img/icons/tennis.svg
  client/src/assets/img/icons/weight.svg
  client/src/assets/img/icons/yoga.svg
  client/src/components/UI/atoms/CommentViewer.js
  client/src/components/UI/atoms/HistoryCardLayouts.js
  client/src/components/UI/atoms/WriterCardLayouts.js
  client/src/components/UI/molecules/CommentViewer.js
  client/src/components/UI/molecules/CommentViewer_X.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/molecules/WriterCardLayouts.js
  client/src/components/UI/molecules/WriterCardLayouts_X.js
  client/tailwind.config.js
Labels: Front, Feat

#59 ✨feat : review 질문 컴포넌트 구현
  client/src/assets/img/icons/reviewMark.svg
  client/src/components/UI/atoms/LightBtn.js
  client/src/components/UI/molecules/ReviewMent.js
Labels: Front, Feat

#61 ✨ Feat: 대댓글 작성 POST API
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/dto/CommentSimpleResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/controller/ReplyController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/dto/ReplyPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/dto/ReplyResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/entity/Reply.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/mapper/ReplyMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/repository/ReplyRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/service/ReplyService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/service/ReplyServiceImpl.java
Labels: Back, Feat

#65 📝docs: readme init
  Readme.md
Labels: Docs

#66 ✨feat: Add molecules Aplicant
  client/src/components/UI/molecules/Applicant.js
Labels: Front, Feat

#62 ✨ Feat : 유저 선택요소 컴포넌트 구현
  client/src/components/UI/atoms/ChooseBtn.js
  client/src/components/UI/atoms/Datepicker.js
  client/src/components/UI/atoms/index.js
  client/src/components/UI/molecules/Dropdown.js
  client/src/components/UI/molecules/GenderSelect.js
  client/src/components/UI/molecules/TownSelect.js
  client/src/components/UI/molecules/WriteDate.js
  client/src/components/UI/molecules/WriteGenderSelect.js
Labels: Front, Feat

#63 ✨Feat : 리뷰 모달 구현
  client/src/components/UI/atoms/MiniBtn.js
  client/src/components/UI/molecules/ArounderReview.js
  client/src/components/UI/molecules/ReviewMent.js
  client/src/components/UI/molecules/index.js
  client/src/components/UI/organisms/Modal.js
  client/src/index.css
Labels: Front, Feat

#68 ✨feat: Add Header
  client/src/assets/img/icons/info.svg
  client/src/assets/img/icons/leftArrow.svg
  client/src/assets/img/icons/logo.svg
  client/src/assets/img/icons/menu.svg
  client/src/components/UI/molecules/HeaderArrow.js
  client/src/components/UI/molecules/HeaderFind.js
  client/src/components/UI/molecules/HeaderLogo.js
Labels: Front, Feat

#67 ✨ Feat: 대댓글 삭제 DELETE API
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/controller/ReplyController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/service/ReplyService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/service/ReplyServiceImpl.java
Labels: Back, Feat

#69 ✨ Feat : 홈화면 카드 컴포넌트 구현
  client/src/components/UI/atoms/CommentLayout.js
  client/src/components/UI/atoms/ExerciseBtn.js
  client/src/components/UI/atoms/HomeCardLayouts.js
  client/src/components/UI/atoms/WriterCommentLayout.js
  client/src/components/UI/molecules/CommentViewer.js
  client/src/components/UI/molecules/CommentViewer_X.js
  client/src/components/UI/molecules/WriterCardLayouts.js
  client/src/components/UI/molecules/WriterCardLayouts_X.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/utils/getIcon.js
Labels: Front, Feat

#56 ✨ Feat: 리뷰 POST API
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberSimpleDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/controller/ReviewController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/entity/Review.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/mapper/ReviewMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/repository/ReviewRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/service/ReviewService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#70 ✨feat: 배터리 컴포넌트 구현
  client/src/components/UI/atoms/BatteryCase.js
  client/src/components/UI/atoms/Charging.js
  client/src/components/UI/atoms/index.js
Labels: Front, Feat

#71 ✨feat: mypage info 구현
  client/src/components/UI/organisms/MyInfo.js
Labels: Front, Feat

#73 ✨feat: Add ORG Comments
  client/src/assets/img/icons/recomment.svg
  client/src/components/UI/atoms/CommentBtn.js
  client/src/components/UI/atoms/TextInput.js
  client/src/components/UI/atoms/WriterCommentLayout.js
  client/src/components/UI/molecules/CommentViewer.js
  client/src/components/UI/molecules/CommentViewer_X.js
  client/src/components/UI/molecules/InputComments.js
  client/src/components/UI/molecules/WriterCardLayouts.js
  client/src/components/UI/molecules/WriterCardLayouts_X.js
  client/src/components/UI/organisms/Comments.js
Labels: Front, Feat

#75 ✨Feat: Drawer 구현
  client/src/assets/img/icons/addPeople.svg
  client/src/assets/img/icons/mypage.svg
  client/src/components/UI/atoms/Drawer.js
  client/src/components/UI/atoms/LogoutBtn.js
  client/src/components/UI/atoms/index.js
  client/src/components/UI/molecules/DrawerInfo.js
  client/src/components/UI/molecules/index.js
  client/src/components/UI/organisms/Drawer.js
Labels: Front, Feat

#76 ✨feat: Add ORG Arounder Record
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/organisms/ArounderRecord.js
  client/src/components/UI/organisms/Comments.js
  client/src/components/UI/organisms/DetailContents.js
Labels: Front, Feat

#77 :adhesive_bandage: chore: ddl auto update로 변경
  server/src/main/resources/application.yml
Labels: Back, Chore

#80 ✨ Feat: 시작시 주소 초기화 세팅 및 주소엔티티 컬럼명 변경
  server/src/main/java/com/ilchinjo/mainproject/domain/address/entity/Address.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
Labels: Back, Feat

#81 ✨ Feat: 회원과 운친모집에 주소 등록 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/address/dto/AddressResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseDetailResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/mapper/ExerciseMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberDetailResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Feat

#82 ✨ Feat: 신청 상태 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/ProposalStatus.java
Labels: Back, Feat

#90 ✨Feat: 토글 구현
  client/src/assets/img/icons/man.svg
  client/src/assets/img/icons/toggleAll.svg
  client/src/assets/img/icons/woman.svg
  client/src/components/UI/atoms/Toggle.js
  client/src/components/UI/atoms/index.js
Labels: Front, Feat

#84 ✨ Feat: logging 설정
  .gitignore
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/ilchinjo/mainproject/global/config/AppConfig.java
  server/src/main/java/com/ilchinjo/mainproject/global/config/P6spySqlFormatConfiguration.java
  server/src/main/resources/application.yml
  server/src/main/resources/logback-spring.xml
Labels: Back, Feat

#83 ✨ Feat: 댓글 전체 조회 GET API
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/dto/CommentDetailResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/mapper/CommentMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/repository/CommentRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/dto/CursorResponseDto.java
Labels: Back, Feat

#85 🩹chore: Add index import & export code
  client/src/components/UI/atoms/index.js
  client/src/components/UI/molecules/index.js
Labels: Front, Feat

#93 ✨ Feat: 로그인 페이지 템플릿 구현
  client/src/components/UI/molecules/HeaderArrow.js
  client/src/components/UI/molecules/HeaderFind.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/molecules/HeaderNone.js
  client/src/components/UI/molecules/index.js
  client/src/components/templates/LoginTemplate.js
Labels: Front, Feat

#94 ✨ Feat: 회원가입 페이지 템플릿 구현
  client/src/components/UI/atoms/ImgAddBtn.js
  client/src/components/UI/atoms/SignupImg.js
  client/src/components/UI/atoms/index.js
  client/src/components/UI/molecules/GenderSelect.js
  client/src/components/templates/RegisterTemplate.js
Labels: Front, Feat

#101 ♻️ Refactor: 신청, 리뷰 중복에 대한 테이블 제약조건 설정
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/entity/Review.java
Labels: Back, Refactor

#107 ✨feat: 글쓰기 템플릿 구현
  client/src/components/UI/atoms/FileDeleteBtn.js
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/atoms/index.js
  client/src/components/UI/molecules/AddFile.js
  client/src/components/UI/molecules/index.js
  client/src/components/UI/organisms/WriteContents.js
  client/src/components/templates/WriteTemplate.js
Labels: Front, Feat

#109 ✨feat: 메인페이지 템플릿 구현
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/components/templates/MainTemplate.js
  client/tailwind.config.js
Labels: Front, Feat

#113 :recycle: refactor: url 전부 복수형으로 통일
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/controller/ReviewController.java
Labels: Back, Chore

#116 ✨ feat: 툴팁 구현 및 프롭스 수정
  client/src/components/UI/molecules/HeaderLogo.js
Labels: Front, Feat

#119 🐛 Fix : 로그인 페이지 템플릿 수정
  client/src/components/UI/molecules/IdInput.js
  client/src/components/UI/molecules/PasswordInput.js
  client/src/components/templates/LoginTemplate.js
Labels: Front, Fix

#122 🐛 Fix: 회원가입 페이지 템플릿 수정
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/molecules/CheckPasswordInput.js
  client/src/components/UI/molecules/Dropdown.js
  client/src/components/UI/molecules/GenderSelect.js
  client/src/components/UI/molecules/IdInput.js
  client/src/components/UI/molecules/NickNameInput.js
  client/src/components/UI/molecules/PasswordInput.js
  client/src/components/UI/molecules/TownSelect.js
  client/src/components/UI/molecules/index.js
  client/src/components/templates/RegisterTemplate.js
Labels: Front, Fix

#121 ✨Feat: Mypage 템플릿 구현
  client/src/components/UI/atoms/MiniBtn.js
  client/src/components/UI/molecules/ArounderReview.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/molecules/NicknameMypage.js
  client/src/components/UI/organisms/ArounderRecord.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/UI/organisms/Modal.js
  client/src/components/UI/organisms/MyInfo.js
  client/src/components/templates/MypageTemplate.js
  client/src/index.css
Labels: Front, Feat

#124 ✨ Feat: 회원 마이페이지 운동기록 구현
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseRecordDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberDetailResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
Labels: Back, Feat

#112 ✨ Feat: 이미지 처리 로직 구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/config/AwsS3Config.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/dto/ImageResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/mapper/ImageMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/repository/ImageRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/service/ImageService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/service/ImageServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPostDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: Back, Feat

#128 🎨styling: index 추가
  client/src/assets/img/icons/index.js
  client/src/assets/img/index.js
  client/src/components/UI/atoms/CommentDeleteBtn.js
  client/src/components/UI/atoms/DeleteBtn.js
  client/src/components/UI/atoms/DrawerLayout.js
  client/src/components/UI/atoms/EditBtn.js
  client/src/components/UI/atoms/FileDeleteBtn.js
  client/src/components/UI/atoms/ImgAddBtn.js
  client/src/components/UI/atoms/LightBtn.js
  client/src/components/UI/atoms/Toggle.js
  client/src/components/UI/atoms/UpdateBtn.js
  client/src/components/UI/atoms/index.js
  client/src/components/UI/index.js
  client/src/components/UI/molecules/DrawerInfo.js
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/UI/molecules/HeaderArrow.js
  client/src/components/UI/molecules/HeaderFind.js
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/molecules/HistoryCards.js
  client/src/components/UI/molecules/MiniDropdown.js
  client/src/components/UI/molecules/NicknameMypage.js
  client/src/components/UI/molecules/ReviewMent.js
  client/src/components/UI/molecules/TownSelect.js
  client/src/components/UI/molecules/index.js
  client/src/components/UI/organisms/Comments.js
  client/src/components/UI/organisms/Drawer.js
  client/src/components/UI/organisms/index.js
  client/src/components/templates/LoginTemplate.js
  client/src/components/templates/MainTemplate.js
  client/src/components/templates/MypageTemplate.js
  client/src/components/templates/RegisterTemplate.js
  client/src/components/templates/WriteTemplate.js
  client/src/utils/getIcon.js
Labels: Front, Chore

#132 ✨ Feat: 운동모집글 전체조회
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseSimpleResponseDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/mapper/ExerciseMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepository.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryCustom.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryCustomImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
Labels: Back, Feat

#129 🐛 Bug: 회원 정보 수정 로직 변경
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacelong/NotSpaceLong.java
  server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacelong/NotSpaceLongValidator.java
  server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacestring/NotSpaceString.java
  server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacestring/NotSpaceStringValidator.java
Labels: Back, Fix

#131 🩹 Chore: yml profile 설정
  server/src/main/resources/application-common.yml
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: Back

#114 ✨ Feat: Spring Security JWT 인증 구현
  server/build.gradle
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/reply/controller/ReplyController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/controller/ReviewController.java
  server/src/main/java/com/ilchinjo/mainproject/global/config/WebConfig.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/dto/LoginDto.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/handler/LoginSuccessMemberInfo.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/jwt/JwtTokenizer.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/userdetails/MemberDetailsService.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/ilchinjo/mainproject/global/security/utils/ErrorResponder.java
Labels: Back, Feat

#133 ♻️ Refactor: 운동모집 상세 조회에 host/proposal 정보 포함
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseDetailResponseDto.java
Labels: Back, Fix

#136 ✨ Feat : 회원가입 페이지 구현
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/client/client.js
  client/src/components/UI/atoms/ChooseBtn.js
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/molecules/CheckPasswordInput.js
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/UI/molecules/GenderSelect.js
  client/src/components/UI/molecules/IdInput.js
  client/src/components/UI/molecules/NickNameInput.js
  client/src/components/UI/molecules/PasswordInput.js
  client/src/components/UI/molecules/TownSelect.js
  client/src/components/pages/ArounderViewer.js
  client/src/components/pages/ArounderWriter.js
  client/src/components/pages/Landing.js
  client/src/components/pages/LoginTemplate.js
  client/src/components/pages/MainTemplate.js
  client/src/components/pages/MypageTemplate.js
  client/src/components/pages/Register.js
  client/src/components/pages/WriteTemplate.js
  client/src/components/templates/RegisterTemplate.js
Labels: Front, Feat

#144 ✨ Feat : 로그인 페이지 구현
  client/src/components/pages/Login.js
  client/src/components/pages/Register.js
Labels: Front, Feat

#149 ✨ Feat : 회원가입 페이지 추가 구현
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/pages/Register.js
Labels: Front, Feat

#151 ✨ Feat : 메인 페이지 추가 구현
  client/src/components/pages/LoginTemplate.js
  client/src/components/pages/Main.js
Labels: Front, Feat

#152 ✨ Feat: 라우터 수정
  client/src/App.js
  client/src/components/pages/RegisterTemplate.js
Labels: Front, Feat

#147 🐛 Bug: SecurityConfiguration의 권한 부여 설정 변경
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
Labels: Back, Fix

#148 🐛 Bug: 댓글을 삭제하면 대댓글도 삭제되도록 수정
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/entity/Comment.java
Labels: Back, Fix

#154 :adhesive_bandage: Chore: 운동모집글 삭제 핸들러메서드 파라미터 변경
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
Labels: Back, Fix

#155 🐛 Bug: 실행시마다 주소가 중복되어 저장되는 문제 수정
  server/src/main/java/com/ilchinjo/mainproject/domain/address/entity/Address.java
  server/src/main/resources/data.sql
Labels: Back, Fix

#158 🐛 Bug: hasNext 버그 수정 및 성능 개선
  server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
Labels: Back, Fix

#157 🐛 Bug: 운동모집글 전체조회 핸들러메서드 파라미터 변경
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
Labels: Back, Fix

#160 🐛 Bug: 회원 정보 수정 시에 수정하려는 사람이 본인이 맞는지 검증
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
Labels: Back, Fix

#161 :bug: Bug: 애플리케이션 실행시 yml파일을 읽어오지 못하는 오류 해결
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: Back, Fix

#163 🐛 Bug: cors관련 오류 수정
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
Labels: Back, Fix

#162 :bug: Bug: CORS 설정 수정
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
Labels: Back, Fix

#164 :bug: Bug: 운동시작 시간이 종료시간보다 늦을 경우의 예외처리 로직 생성
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Fix

#165 🐛 Bug: 운동시작 시간이 현재 시간보다 이를 경우의 예외처리 로직 생성
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
Labels: Back, Fix

#166 🐛 Fix: proposalStatus가 null로 나오던 문제 수정
  server/src/main/java/com/ilchinjo/mainproject/domain/proposal/mapper/ProposalMapper.java
Labels: Back, Fix

#171 ✨ feat: 운동모집 전체조회 시 작성자 정보 포함
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseResponseDto.java
Labels: Back, Chore, Feat

#172 ✨ Feat: 회원정보 간단조회 api추가
  server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberSimpleDto.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java
  server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java
  server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
Labels: Back, Feat

#173 ✨ Feat: 데이터 패칭
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/atoms/Toggle.js
  client/src/components/UI/molecules/ExerciseCarousel.js
  client/src/components/pages/Login.js
  client/src/components/pages/Main.js
  client/src/components/pages/Register.js
  client/src/utils/getIcon.js
Labels: Front, Feat

#177 ✨ feat: 데이터 추가 연결
  client/src/components/UI/atoms/HomeCardLayouts.js
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/UI/molecules/MiniDropdown.js
  client/src/components/UI/molecules/TownSelect.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/components/pages/Login.js
  client/src/components/pages/Main.js
  client/src/components/pages/Register.js
Labels: Front, Feat

#175 ✨ Feat: 시큐리티 config path 규칙 변경
  server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
Labels: Back, Chore, Feat

#178 ✨Feat: 글쓰기 페이지 구현
  client/package.json
  client/src/App.js
  client/src/client/client.js
  client/src/components/UI/atoms/LongBtn.js
  client/src/components/UI/molecules/AddFile.js
  client/src/components/UI/molecules/ExerciseCategory.js
  client/src/components/UI/molecules/WriteGenderSelect.js
  client/src/components/UI/molecules/WriteHNC.js
  client/src/components/UI/organisms/WriteContents.js
  client/src/components/pages/Write.js
  client/src/components/pages/WriteTemplate.js
Labels: Front, Feat

#180 🩹chore: code del comments by index.js
  client/src/components/UI/organisms/index.js
Labels: Front, Fix

#186 ✨Feat: 메인페이지 추가 구현
  client/src/components/UI/atoms/EditBtn.js
  client/src/components/UI/atoms/HomeCardLayouts.js
  client/src/components/UI/molecules/DropdownCity.js
  client/src/components/UI/molecules/MiniDropdown.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/components/pages/Main.js
  client/src/components/pages/Register.js
Labels: Front, Feat

#189 ✨ feat: 메인페이지 추가 구현
  client/src/components/UI/molecules/HeaderLogo.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/components/pages/Main.js
  client/src/components/pages/MypageTemplate.js
Labels: Front, Feat

#191 :adhesive_bandage: Chore: ExerciseDetailResponseDto에 images 추가
  server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseDetailResponseDto.java
Labels: Back, Fix

#192 #174 ✨메인페이지 추가 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/UI/atoms/HomeCardLayouts.js
  client/src/components/UI/atoms/Toggle.js
  client/src/components/UI/organisms/HomeContents.js
  client/src/components/pages/Main.js
  client/src/recoil/atoms.js
Labels: Front, Feat
